In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [3]:
a_list = [1,2,3]

In [4]:
array = np.array(a_list)

In [5]:
array

array([1, 2, 3])

In [6]:
a_listt = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
array2 = np.array(a_listt)

In [8]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arrr = np.zeros(2)

In [10]:
arrr

array([0., 0.])

In [11]:
arrr2 = np.ones((2,2))

In [12]:
arrr2

array([[1., 1.],
       [1., 1.]])

In [13]:
np.random.rand(2,2)

array([[0.47912007, 0.34979707],
       [0.64636997, 0.4693398 ]])

In [14]:
  array = np.random.randint(0,100,16)

In [15]:
array

array([78, 49, 57, 43,  8, 74, 35, 65, 92,  4, 47, 76, 69, 50, 37,  4])

In [16]:
array.shape

(16,)

In [17]:
 array.ndim

1

In [18]:
array.reshape(4,4)

array([[78, 49, 57, 43],
       [ 8, 74, 35, 65],
       [92,  4, 47, 76],
       [69, 50, 37,  4]])

In [19]:
arr2d = array.reshape(4,4)

In [20]:
arr2d.ndim

2

In [21]:
arr2d.shape

(4, 4)

In [22]:
array.dtype

dtype('int32')

In [25]:
array = np.arange(1,10)

In [26]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
array[4]

5

In [29]:
array[2:5]

array([3, 4, 5])

In [30]:
array2d = array.reshape(3,3) 

In [31]:
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
array2d[2:3, 1:2]

array([[8]])

In [1]:
array = np.arrange(1,10)

NameError: name 'np' is not defined