In [1]:
import numpy as np

In [2]:
array= np.arange(1,10)

In [3]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
array[0:3]

array([1, 2, 3])

In [5]:
array2 = array.reshape(3,3)

In [6]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
array2[0,2]

3

In [8]:
array2[:1]

array([[1, 2, 3]])

In [9]:
array2[0,2]

3

In [10]:
array2[1,2]

6

In [11]:
array2[1,2]

6

In [12]:
array2[2,2]

9

In [13]:
array2[2:1]

array([], shape=(0, 3), dtype=int32)

In [14]:
array2[0,2]

3

In [15]:
array[0:1]

array([1])

In [16]:
array[1:1]

array([], dtype=int32)

In [17]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
array2[0]

array([1, 2, 3])

In [19]:
 array2[0:1]

array([[1, 2, 3]])

In [20]:
array2[0:1]

array([[1, 2, 3]])

In [21]:
array2[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
array2[0:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
array2[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
array2[0:2,0:1]

array([[1],
       [4]])

In [25]:
array2[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [26]:
array2.max()

9

In [27]:
array2.max(axis=0)

array([7, 8, 9])

In [28]:
array2.max(axis=1)


array([3, 6, 9])

In [29]:
array = np.array([1,2])

In [30]:
array

array([1, 2])

In [31]:
array3 = np.array([4,5])

In [32]:
array3

array([4, 5])

In [33]:
predictions = np.array([2,5,6])
labels = np.array([1,5,8])

In [34]:
MSE = (1/3)*np.sum(np.square(predictions - labels))

In [35]:
MSE

1.6666666666666665

In [36]:
MSE:.2f

SyntaxError: invalid syntax (<ipython-input-36-b5af7e2fc6fe>, line 1)

In [37]:
my_list =[40,2,1,52,34]

In [38]:
state = ['Lagos','Delta','Kaduna']

In [39]:
state_dictionary = {'Lagos':'Ikeja','Delta':'Asaba','kaduna':'Kaduna'}

In [40]:
ser = pd.Series(state_dictionary)

NameError: name 'pd' is not defined

In [41]:
import pandas as pd

In [42]:
ser = pd.Series(state_dictionary)

In [43]:
ser

Lagos      Ikeja
Delta      Asaba
kaduna    Kaduna
dtype: object